Add isModuleEnabled function
calamares/calamares pull request #1809
Opened 2021-10-23 18:59 UTC by dalto8

This is a simple function to make checking if a modules is enabled in settings.conf easier.

2021-10-26 10:38 UTC, adriaandegroot requested changes
There's some const-bits and code-cleanup that needs doing, alongside some nits.

2021-10-26 10:38 UTC, adriaandegroot commented on src/libcalamares/Settings.h
> +    bool isModuleEnabled( QString module );
- `const QString& module` is idiomatic (even if QString is cheap-to-copy, the reference thing is deeply ingrained)
- method should be `const`
- "Returns whether the named module is enabled" for brief
- Describe that this means "any instance of @p module is listed in the sequence (in a show or an exec part, that does not matter) in settings", make clear that this isn't the same as "@p module is present on the system and could conceivably be used"

2021-10-26 10:38 UTC, adriaandegroot commented on src/libcalamares/Settings.cpp
> +    auto moduleFinder = [ &targetKey ]( const InstanceDescription& d ) { return d.isValid() && d.key() == targetKey; };
This is a spurious change. Calamares uses clang-format 8 or clang-format 9 **only**. There are some really annoying changes between clang-format 9 and 10, so that it's not possible to keep a "clean" formatting while using both versions. You end up with endless ping-ponging of spaces in lambdas.

(That said, I am inclined to revise the coding style for Calamares 3.3 so we can use newer versions of the tooling, and have less custom-configuration involved)

2021-10-26 10:38 UTC, adriaandegroot commented on src/libcalamares/Settings.cpp
> +Settings::isModuleEnabled( QString module )
See comments on consts and references in the header file.

2021-10-26 10:38 UTC, adriaandegroot commented on src/libcalamares/Settings.cpp
> +    for ( const auto& moduleInstance : Calamares::Settings::instance()->moduleInstances() )
`isModuleEnabled()` is a member function, you don't have to re-direct through `instance()` (which might even be a **different** Settings object!). Just iterate over `moduleInstances()`, or better yet, `m_moduleInstances`. This looks like an artifact of copying a free function (which needs to get the list of instances in this fashion) into a member function.

2021-10-26 10:38 UTC, adriaandegroot commented on src/libcalamares/Settings.cpp
> +        if ( moduleInstance.key().first == module )
Please use `{ }` around all blocks (the style-tool should do that already, but astyle is sometimes a bit hard-of-learning).

You can use `moduleInstance.key().module() == module` to avoid the implementation knowledge that the module-key (e.g. *packagechooser*) is first.

2021-10-26 10:38 UTC, adriaandegroot commented on src/libcalamares/Settings.h
> +    bool isModuleEnabled( QString module );
This should probably emphasize that `@p module` is a module name, or module key (e.g. *packagechooser*) and not a full module key+id (e.g. *packagechooser@packagechooser* or *shellprocess@before_user*). It also doesn't consider QML and non-QML versions of a module "the same"; this is something that will eventually change when the Q-or-not-Q decision is not reflected in the module's identity, but in its configuration.

2021-10-26 11:32 UTC, dalto8 commented on src/libcalamares/Settings.h
> +    bool isModuleEnabled( QString module );
> This should probably emphasize that `@p module` is a module name, or module key (e.g. _packagechooser_) and not a full module key+id (e.g. _packagechooser@packagechooser_ or _shellprocess@before_user_).

Although I don't need it in my implementation, would it be useful to add a bool to allow to check either case?  The module key or the key+id?

> It also doesn't consider QML and non-QML versions of a module "the same";

Should it?  If so, is the only difference a leading "q" in the name?

2021-10-26 15:19 UTC, adriaandegroot commented on src/libcalamares/Settings.h
> +    bool isModuleEnabled( QString module );
These were more "bear in mind that.." kinds of comments from me. I don't think that checking for *module@id* is useful; the *id* part serves to distinguish different instances of the same module, when you need it more than once (e.g. multiple netinstalls, or multiple shellprocesses, those are the most common cases). I can't usefully imagine a module checking for a specific instance of a different module -- at some point the problem becomes "fix your distro's configuration". (e.g. what would checking for *shellprocess@you_can_call_me_al* even **mean** in a general context?)

This is probably something that is up to the caller, not the function implementing the check; is a module satisfied if *packagechooser* is enabled? How about *packagechooserq*? Either? Both? That's up to the caller.

2021-10-28 19:47 UTC, dalto8 commented on src/libcalamares/Settings.cpp
> +    for ( const auto& moduleInstance : Calamares::Settings::instance()->moduleInstances() )
Yep, I was testing it elsewhere and then copied here.  Fixed now.

2021-10-28 20:06 UTC, dalto8 commented
This should be ready for review again.

2021-10-29 09:20 UTC, merged