[partition] Allow specifying unencrypted partitions when LUKS is in use
calamares/calamares pull request #2280
Opened 2024-02-05 23:50 UTC by ArrayBolt3

Implements feature request https://github.com/calamares/calamares/issues/1938 sorta. There's no user-visible checkbox for encrypting or not encrypting `/boot`, instead there is an additional `noEncrypt` option added to the `partitionLayout` section of `partition.conf`, allowing a distro to specify that a certain partition should remain unencrypted even when encryption is enabled.

2024-02-05 23:51 UTC, ArrayBolt3 commented on src/modules/partition/core/PartitionLayout.h
gah, Vim struck again and did a weird mix of spaces plus tabs. Fixing...

2024-02-05 23:52 UTC, ArrayBolt3 commented on src/modules/partition/core/PartitionLayout.h
Fixed.

2024-02-06 00:00 UTC, ArrayBolt3 commented
I'm realizing I didn't make this work right with ZFS partitions. I probably should go through and fix that.

2024-02-06 00:06 UTC, ArrayBolt3 commented
alright, that should work with ZFS encryption too. I did **not** test whether this results in unencrypted ZFS or not yet, but  I believe it will work as the logic is very straightforward.

2024-02-06 01:18 UTC, dalto8 requested changes

2024-02-06 01:18 UTC, dalto8 commented on src/modules/partition/core/PartitionLayout.cpp
> +                          Calamares::getBool( pentry, "noEncrypt", true ),
This should be `false` by default to mirror the prior behavior.

2024-02-06 01:18 UTC, dalto8 commented on src/modules/partition/partition.conf
> +#   - noEncrypt: whether this partition is exempt from encryption if enabled (optional parameter)
We should mention the default state.

2024-02-06 01:18 UTC, dalto8 commented on src/modules/partition/core/PartitionLayout.cpp
> +        if ( luksPassphrase.isEmpty() || correctFS( entry.partFileSystem ) == FileSystem::Zfs || entry.partNoEncrypt )
We need to update the comment above this to reflect these changes.

2024-02-06 01:22 UTC, ArrayBolt3 commented on src/modules/partition/core/PartitionLayout.cpp
> +                          Calamares::getBool( pentry, "noEncrypt", true ),
Good catch, that was an accident. Fixing now.

2024-02-06 01:37 UTC, ArrayBolt3 commented
Got all changes implemented. (The default variable thing was a mistake since I went from implementing this as an `isEncryptable` option that defaulted to true, to a `noEncrypt` option that defaulted to false, and then forgot to change the default.)

2024-02-06 01:38 UTC, dalto8 commented
I will take a look at it more depth tomorrow.  If memory serves, that isn't the only place we do the partition layout.

The partition module is quite a mess.

2024-02-06 02:06 UTC, ArrayBolt3 commented
Thanks!

I did a quick look through and the only other place I saw where
encrypted partitions are made is in PartitionActions.cpp, where an
(optionally encrypted) swap partition is made. I don't particularly
mind if the swap partition is *always* encrypted when encryption is
used - unencrypted swap breaks the security of FDE pretty much
entirely (at best it's a gaping security hole), and if someone's that
determined to configure their system in a broken way, they can use the
manual partitioning screen.

In case it's helpful, I did patch Ubuntu's Calamares locally with (the
earlier version of) these changes and successfully used it to make an
encrypted Kubuntu installation with unencrypted /boot without doing
manual partitioning.

On Mon, Feb 5, 2024 at 7:38 PM dalto8 ***@***.***> wrote:
>
> I will take a look at it more depth tomorrow. If memory serves, that isn't the only place we do the partition layout.
>
> The partition module is quite a mess.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-02-08 01:31 UTC, dalto8 approved these changes

2024-02-08 19:58 UTC, dalto8 approved these changes

2024-02-08 19:58 UTC, merged